### ISSUE TITLE
Static access to string resources

### ISSUE THREAD

**Issue by fgroeger** [liamnichols/xcstrings-tool#113]
Right now it is only possible to access strings like this:
```swift
String(localizable: .myText)
```

However, in SwiftUI I can access it as easy like this:
```swift
Text(.localizable(.myText))
```

My team and me prefer the SwiftUI way to access the strings. We still have a lot of UIKit in our codebase, so we would like to have a similar easy access to the strings directly.

Proposal:
```swift
label.text = .localizable(.myText)
```

If you would be open for that addition, I'd love to create a PR for this. Just tell me your thoughts.

Thanks!

**Comment by liamnichols** [comment]
Hello @fgroeger! Oh great, thank you for raising this, and thanks for the PR! 

I just need to double check that it doesn't cause any unexpected ambiguity when selecting the appropriate version in SwiftUI. It might be that we need to use `@_disfavoredOverload` or something like that

**Comment by liamnichols** [comment]
From a quick test, it looks good to me:

<img width="1464" alt="Screenshot 2024-09-16 at 13 56 06" src="https://github.com/user-attachments/assets/ea14794f-24a8-423a-9f91-c9febf607ece">

For context, the reason that I wanted to be sure is that initing Strings is a little different to `LocalizedStringKey`/`LocalizedStringResource` because the `String` initialiser will resolve the localized value immediately whereas `LocalizedStringKey`/`LocalizedStringResource` are deferred until the view is rendered (and the SwiftUI environment is available). 

As long as SwiftUI will continue to correctly use the `LocalizedStringKey`/`LocalizedStringResource` versions, all is good though 👍 

```swift
localized(.foo) as String // Localization lookup happens immediately 
localized(.foo) as LocalizedStringKey // Localization lookup deferred until view is rendered
```

**Comment by fgroeger** [comment]
Hey @liamnichols, thank you for integrating the changes. Looking forward to use version 1.0 in our application!
