### ISSUE TITLE
Support macOS 12/iOS 15/etc by using String(localized:) instead of LocalizedStringResource

### ISSUE THREAD

**Issue by andrewtheis** [liamnichols/xcstrings-tool#30]
Currently the plugin generates the `static let` properties as a `LocalizedStringResource`, but `String` has an initializer that works with String Catalogs as well:

`public init(localized key: StaticString, defaultValue: String.LocalizationValue, table: String? = nil, bundle: Bundle? = nil, locale: Locale = .current, comment: StaticString? = nil)`

Using `String` rather than `LocalizedStringResource` will allow this library to support macOS 12/iOS 15/etc.

If you're working with features that utilize XPC and need locale lookups to happen on the fly, this would break that functionality. But I can't imagine that's very common currently.

**Comment by liamnichols** [comment]
Hey, thanks for the suggestion!

I did consider this, but initially didn’t go with it for a couple of reasons:

1. I like to be able to compare `LocalizedStringResource` instances in my tests rather than the resolved localised string values themselves.
2. In the 2023 WWDC session video about String Catalogs, the presenter mentions how `LocalizedStringResource` is the recommended api to use now. I assume mostly because if you pass a custom locale into the environment, you need to let SwiftUI resolve the correct language.
3. Using the existing `LocalizedStringResource` type gave me a good place to define the static properties that allow the nice `Text(.localizable.myString)` syntax.

But that said, I was a bit disappointed that it forced the tool to only be available on iOS 16+ projects while Strings Catalogs themselves back deployed. 

I considered the String initialiser that you referred to, but if we were to support it, I’d want to do so in parallel with the `LocalizedStringResource` extension.

I have a couple of questions though:

1. Using this API only gets 1 extra year of backwards compatibility.. Is it worth it? Or maybe just go back to NSLocalizedString instead? 
2. I’m not too sure where to expose the generated constants. Is extending `String` like I extend `LocalizedStringResource` a controversial decision? And if not, do we have to worry about ambiguous usage in SwiftUI for types that have the same initializer signature for LocalizedStringResource and String?

**Comment by andrewtheis** [comment]
Normally I'm with you on not supporting older versions, however [the application](https://hiddenspectrum.io/producer-toolkit) I have targets an audience (music producers) who are hesitant to upgrade macOS, as it can sometimes break the apps or dozens/hundreds+ of audio plugins they rely on. So it supports macOS 12, which is far back as I can go before SwiftUI becomes unusable. Wish I didn't have to, but it is what it is.

Anyway, extending String definitely wouldn't work in all cases - some APIs you need to do `String.` to get it to resolve.

One possible solution would be to generate a new type that wraps the String values, and then extend SwiftUI types with convenience `init` that accept those types. One thing that would be interesting about this is you could even make a type for each base SwiftUI component, which could further type constrain at the callsite:

So if you had `text.exampleString` as the key, it would generate:

```
struct LocalizedText {
   // ...
   static let exampleString = LocalizedText(...)
}
```

Then when using `Text()`, only LocalizedText values show. If you omit the prefix from the key, it puts adds it to some generic type that can be used by all SwiftUI types.

This has some downsides though:
- Keeping up with all the `init` methods of SwiftUI types could get cumbersome
- You would need to `include` the swift package anywhere you want to use the added `init` methods.

I spent a lot of time yesterday trying to figure out a good system without this tool. I think for what I'm looking for, macros are probably a better option. I still want the Localized string catalog file to be auto populated, and it'd be cool be able to breakdown by type and component.
 
Macros might as well be a foreign language to me though, and I don't have the time currently to try and figure them out.

Phew, that was a long way to say: I have no idea best approach here 🤷🏻‍♂️. It's frustrating that Apple builds new systems like this, but then stops just short of it being completely useful 😂

**Comment by Fesh-com** [comment]
> On 2023-12-13, at 22:17:59, Liam Nichols ***@***.***> wrote:
> 
> Using this API only gets 1 extra year of backwards compatibility.. Is it worth it? Or maybe just go back to NSLocalizedString instead?

iOS 15 vs iOS 16 is way more than just “1 extra year of backwards compatibility”, because all iOS devices capable of running iOS 13 and iOS 14 can also run iOS 15.
Thus you gain 3 years of devices - and loose only those which are stuck with iOS 12 or lower.
It really doesn’t make sense to support iOS 14 or 13 anymore, but 15 vs 16 is a big deal.


Marc

**Comment by liamnichols** [comment]
Thanks for all the input here so far.. I just want to circle back to the main motivation for using `LocalizedStringResource` initially:

> If you're working with features that utilize XPC and need locale lookups to happen on the fly, this would break that functionality. But I can't imagine that's very common currently.

I just confirmed my assumption about why `LocalizedStringResource` is preferred for SwiftUI with the following:

```swift
VStack(spacing: 8) {
    // init(_ resource: LocalizedStringResource)
    Text(.localizable.emptyStateHeading) // Pas d'observation

    // init(
    //     _ key: LocalizedStringKey,
    //     tableName: String? = nil,
    //     bundle: Bundle? = nil,
    //     comment: StaticString? = nil
    // )
    Text("\(.localizable.emptyStateHeading)") // Pas d'observation

    // init<S>(_ content: S) where S : StringProtocol
    Text(String(localized: .localizable.emptyStateHeading)) // No Sightings Yet
}
.environment(\.locale, Locale(identifier: "fr"))
```

To summarise the above, if you initialise the `String` yourself, you do so using `Locale.current` which might be different to the locale that you are using in your environment. 

While the number of projects that override the locale in the SwiftUI environment might be small, I want to be mindful of this behavioural difference and to try and avoid confusion should this tool support both `LocalizedStringResource` and `String` directly.

Unfortunately using `LocalizedStringKey` is out of the question because you cannot pass the other information such as a `tableName` or `bundle` (it's passed to `Text` directly). So if we do want to support iOS 15, we have to do so by either backporting with something like your `LocalizedText` suggestion, or just by creating `String` instances directly.

I think that the downsides that you listed are too much for me to want to consider something like `LocalizedText`, so I would lean towards looking for a way to provide similar generated code on `String`.

The first part seems easy:

```swift
extension String {
    struct Localizable {
        var foo: String { String(localized: "foo", defaultValue: "Test") }

        // ...
    }
}
```

But if we were to provide the `static var localizable` property, we'd run into issues:

```swift
extension StringProtocol where Self == String {
    static var localizable: String.Localizable { .init() }
}
```

This has risk of making the `Text(.localizable.foo)` usage ambiguous based on how different SwiftUI views provide different initializers.. For example, `Text` has the `LocalizedStringResource` overload so would use that, but `Button` does not, so you might get mixed behaviour. 

The easy way to avoid this is to just not generate the `StringProtocol` extension, but I want to try and make sure that we convey the differences between the generated `String.Localizable` and `LocalizedStringResource.Localizable` types, but i'm still having a think to see if there is a better approach that doesn't require additional steps for whoever is integrating the tool 🤔

**Comment by liamnichols** [comment]
> iOS 15 vs iOS 16 is way more than just “1 extra year of backwards compatibility”, because all iOS devices capable of running iOS 13 and iOS 14 can also run iOS 15. 
> Thus you gain 3 years of devices - and loose only those which are stuck with iOS 12 or lower. 
> It really doesn’t make sense to support iOS 14 or 13 anymore, but 15 vs 16 is a big deal.

Thanks for the insights @Fesh-com.. In our case, we still have a larger portion of users on iOS 14 that is leaving us to hold off on dropping support for as long as possible.

In some of our markets where lower-end devices are more popular, we see some interesting behaviours:

- Reluctant to upgrade because they believe that the OS will slow their device down
- Can't upgrade due to no storage space
- Afraid to upgrade due to no iCloud backup and no access to a PC for manual backup

But you're right, while these are all obstacles, they still don't require you to spend money on a new device so can be overcome if the motivation is there. iOS 15 is probably good enough.

**Comment by liamnichols** [comment]
I guess one option to differentiate the `String` extension from the `LocalizedStringResource` one might be to provide the ability to pass the `Locale` that is used for resolution:

```swift
extension String {
    struct Localizable {
        let locale: Locale

        var foo: String { String(localized: "foo", defaultValue: "Test", locale: locale) }

        // ...
    }
}

extension StringProtocol where Self == String {
    static func localizable(locale: Locale) -> String.Localizable {
        String.Localizable(locale: locale)
    }
}
```

Making changing the static property on `StringProtocol` to a function helps to make the intention a bit clearer since you learn that this method resolves the localized string rather than deferring that to within the SwiftUI environment. 

```swift
Text(.localizable(locale: .current).foo)
Text(.localizable.foo)
```

But providing a locale for each string is a bit verbose... We _could_ provide a default value, but then I worry that it makes the change too subtle 🤔 

```swift
Text(.localizable().foo)
Text(.localizable.foo)
```

**Comment by liamnichols** [comment]
The other approach might just be to do this:

```swift
extension String {
    struct Localizable {
        static func foo(locale: Locale = .current) -> String { 
            String(localized: "foo", defaultValue: "Test", locale: locale) 
        }

        // ...
    }
}
```

So that if you want to use this, you have to do things the old way:

```swift
Text(String.Localizable.foo())
```

While I don't like it so much, maybe it is better than nothing.

My only worry here is that there isn't a clear migration path to using `LocalizedStringResource` longer term... 

But then again, maybe that is fine 😄

**Comment by andrewtheis** [comment]
If the developer is overriding the locale via the environment variable, and it already doesn't work with `String`, then I think the solution here would maybe just provide 2 different plugin targets...

`XCStringsToolPlugin`
`XCStringsToolLegacyPlugin`

Or whatever names make sense. Then internally it just sets a config to generate files with either `LocalizedStringResource` or `String`. 

I didn't see the ability in the SPM docs for pre-build plugins to allow configuration options so this is probably the easiest path forward.

**Comment by lpbas** [comment]
Great suggestions by both of you! 
Is there a plan of supporting iOS 15 through any of these in the near future? We are at the beginning of supporting localization for our app and looking for a proper solution to generate static references to keys from our string catalogs, but we need to support iOS 15, so we can't use this great tool as is.

**Comment by liamnichols** [comment]
So overall, something like this:

```swift
import Foundation

@available(macOS 12, iOS 15, tvOS 15, watchOS 8, *)
extension String {
    public struct Localizable {
        public enum BundleDescription: Sendable {
            case main
            case atURL(URL)
            case forClass(AnyClass)
        }

        public let key: StaticString
        public let defaultValue: LocalizationValue
        public let table: String?
        public var locale: Locale = .current
        public var bundle: BundleDescription

        public init(
            _ key: StaticString,
            defaultValue: LocalizationValue,
            table: String? = nil,
            locale: Locale = .current,
            bundle: BundleDescription = .main
        ) {
            self.key = key
            self.defaultValue = defaultValue
            self.table = table
            self.locale = locale
            self.bundle = bundle
        }
    }

    public init(localizable: Localizable) {
        self.init(
            localized: localizable.key,
            defaultValue: localizable.defaultValue,
            table: localizable.table,
            bundle: .from(description: localizable.bundle),
            locale: localizable.locale
        )
    }
}

@available(macOS 12, iOS 15, tvOS 15, watchOS 8, *)
extension String.Localizable {
    /// This is just a basic string with no arguments
    public static var demoBasic: Self {
        Self(
            "demo.basic",
            defaultValue: ###"A basic string"###,
            table: "Localizable",
            bundle: .current
        )
    }

    // ...
}

@available(macOS 12, iOS 15, tvOS 15, watchOS 8, *)
private extension String.Localizable.BundleDescription {
#if !SWIFT_PACKAGE
    class BundleLocator {
    }
#endif

    static var current: Self {
#if SWIFT_PACKAGE
        .atURL(Bundle.module.bundleURL)
#else
        .forClass(BundleLocator.self)
#endif
    }
}

@available(macOS 12, iOS 15, tvOS 15, watchOS 8, *)
private extension Bundle {
    static func from(description: String.Localizable.BundleDescription) -> Bundle? {
        switch description {
        case .main:
            Bundle.main
        case .atURL(let url):
            Bundle(url: url)
        case .forClass(let anyClass):
            Bundle(for: anyClass)
        }
    }
}

@available(macOS 13, iOS 16, tvOS 16, watchOS 9, *)
private extension LocalizedStringResource.BundleDescription {
    static func from(description: String.Localizable.BundleDescription) -> Self {
        switch description {
        case .main:
            .main
        case .atURL(let url):
            .atURL(url)
        case .forClass(let anyClass):
            .forClass(anyClass)
        }
    }
}

@available(macOS 13, iOS 16, tvOS 16, watchOS 9, *)
extension LocalizedStringResource {
    public struct Localizable {

        /// This is just a basic string with no arguments
        public var demoBasic: LocalizedStringResource {
            LocalizedStringResource(localizable: .demoBasic)
        }

        // ...
    }

    public init(localizable: String.Localizable) {
        self.init(
            localizable.key,
            defaultValue: localizable.defaultValue,
            table: localizable.table,
            locale: localizable.locale,
            bundle: .from(description: localizable.bundle)
        )
    }

    public static let localizable = Localizable()
}
```

**Comment by liamnichols** [comment]
I pushed a draft to the `ln/back-compat` branch if anybody wants to try it (#50)
