### ISSUE TITLE
Unable to compile for tests

### ISSUE THREAD

**Issue by tyiu** [liamnichols/xcstrings-tool#31]
I'm able to build and run just fine with this tool and it works great! But I can't get it to compile for tests.

Here's the commit I'm working on:
https://github.com/tyiu/nos/commit/d3aee1dbc088e0f95fa7a08734b0767026387785

<img width="362" alt="Screenshot 2023-12-14 at 11 31 32 AM" src="https://github.com/liamnichols/xcstrings-tool/assets/963907/ccce07fa-c35f-46d8-84ee-a507e4c6fb04">

Any ideas? Thank you!

**Comment by liamnichols** [comment]
Hey, that is a strange error.. in this instance, is the ExpirationTimeOption.swift file part of the test target or the app target? 

The error mentions that String.LocalizationValue doesn’t have the localizable member, which is true, because localizable is available on an extension of LocalizedStringResource.

Without seeing the code/setup in more detail it is hard to say, but if this file is in your tests, are you sure that the right method that accepts LocalizedStringResource is available in your test code? 

I’m just clicking through on my phone now so I couldn’t navigate the linked commit, but I’ll take more of a look tomorrow if you are still having issues

**Comment by tyiu** [comment]
> Hey, that is a strange error.. in this instance, is the ExpirationTimeOption.swift file part of the test target or the app target?

`ExpirationTimeOption.swift` and a few other files that were showing the error are part of both the app target and test target.

> The error mentions that String.LocalizationValue doesn’t have the localizable member, which is true, because localizable is available on an extension of LocalizedStringResource.
> 
> Without seeing the code/setup in more detail it is hard to say, but if this file is in your tests, are you sure that the right method that accepts LocalizedStringResource is available in your test code?

It should be available. I'm just calling `String(localized: .localizable.myStringKey)`, which is part of `Foundation`.

> I’m just clicking through on my phone now so I couldn’t navigate the linked commit, but I’ll take more of a look tomorrow if you are still having issues

I appreciate it. Thank you!

**Comment by liamnichols** [comment]
> `ExpirationTimeOption.swift` and a few other files that were showing the error are part of **both the app target and test target.**

Hmmm, this might be the issue. 

The generated code will be generated in your app target with the `internal` access level, so your test target wouldn’t see this. 

You would need to `@testable import` the app target in your test target code in order to see it, or alternatively you could opt to [generate the code with the `public` access level](https://swiftpackageindex.com/liamnichols/xcstrings-tool/0.1.1/documentation/documentation/changing-the-access-level). 

But I don’t think that either of these options will work alone if you are just reusing the same file in two targets.

Perhaps in a _different_ file in your test target, you might be able to re-export the accessor? I haven’t tried, but something like this:

```swift
import Foundation 
@testable import struct MyTarget.LocalizedStringResource.Localizable

extension LocalizedStringResource {
    static let localizable = Localizable()
}
```

I haven’t tried this though, but the goal is to make that generated code visible to the test target

**Comment by tyiu** [comment]
> > `ExpirationTimeOption.swift` and a few other files that were showing the error are part of **both the app target and test target.**
> 
> Hmmm, this might be the issue.
> 
> The generated code will be generated in your app target with the `internal` access level, so your test target wouldn’t see this.
> 
> You would need to `@testable import` the app target in your test target code in order to see it, or alternatively you could opt to [generate the code with the `public` access level](https://swiftpackageindex.com/liamnichols/xcstrings-tool/0.1.1/documentation/documentation/changing-the-access-level).
> 
> But I don’t think that either of these options will work alone if you are just reusing the same file in two targets.
> 
> Perhaps in a _different_ file in your test target, you might be able to re-export the accessor? I haven’t tried, but something like this:
> 
> ```swift
> import Foundation 
> @testable import struct MyTarget.LocalizedStringResource.Localizable
> 
> extension LocalizedStringResource {
>     static let localizable = Localizable()
> }
> ```
> 
> I haven’t tried this though, but the goal is to make that generated code visible to the test target

What you suggested didn't work, but I finally fixed it by adding the *.xcstrings files to the test target, and adding the plugin to the build phase of the test target. Which in hindsight was obvious. Thanks for helping me debug! Loving the plugin. Keep it up.

**Comment by liamnichols** [comment]
No worries, I'm glad that you found a workaround!
