### ISSUE TITLE
Add public for package

### ISSUE THREAD

**Issue by Vitalik13** [liamnichols/xcstrings-tool#39]
When I setup XCSTRINGS_TOOL_ACCESS_LEVEL_PUBLIC for my `LocalizationKit` package. I can't get access for generated extension. 

How fix

```swift
func generateLocalizedStringResourceExtension() -> ExtensionDeclSyntax {
        ExtensionDeclSyntax(
            attributes: [
                .attribute(.init(availability: .wwdc2022))
                    .with(\.trailingTrivia, .newline)
            ],
            modifiers: [
                DeclModifierSyntax(name: .keyword(.public)) <======= Need add for access from other package 
            ],
            extendedType: IdentifierTypeSyntax(name: "LocalizedStringResource"),
```

**Comment by liamnichols** [comment]
Hi @Vitalik13! Please can you share some more details about the issue that you are seeing? IIRC, the extension itself _shouldn't_ need the `public` modifier because the property and struct within will have it instead.

You can see the complete generated code here: https://github.com/liamnichols/xcstrings-tool/blob/main/Tests/XCStringsToolTests/__Snapshots__/GenerateTests/testGenerateWithPublicAccessLevel.Localizable.swift

I double checked and updated the demo project to confirm as well: https://github.com/liamnichols/xcstrings-tool-demo/commit/f7d7841d03336d567894c7cbfd192cc74f9f128b

Does this help you?

**Comment by liamnichols** [comment]
I'm going to close this for now as I don't think there is anything to be fixed, but if the above doesn't help then please reopen the issue. Thanks!

**Comment by markst** [comment]
For anyone else landing here, this is resource you might be looking for: 
https://github.com/liamnichols/xcstrings-tool/blob/main/Sources/Documentation/XCStringsToolPlugin.docc/Changing%20the%20Access%20Level.md?plain=1
