### ISSUE TITLE
Build errors after updating from 0.4.1 to higher version

### ISSUE THREAD

**Issue by jmarek41** [liamnichols/xcstrings-tool#99]
Hello,

I cannot build the project after updating from 0.4.1 to 0.4.2 or 0.5.0. I am getting those errors:

```
The package product 'SwiftBasicFormat' requires minimum platform version 13.0 for the iOS platform, but this target supports 12.0
The package product 'SwiftSyntax' requires minimum platform version 13.0 for the iOS platform, but this target supports 12.0
The package product 'SwiftSyntaxBuilder' requires minimum platform version 13.0 for the iOS platform, but this target supports 12.0
```

I use integration directly to Xcode project target (my target has deployment target iOS 16 >) and I followed instructions here: https://swiftpackageindex.com/liamnichols/xcstrings-tool/documentation/documentation/integrating-xcstrings-tool-into-an-xcode-project-target

Since 0.4.1 is working without any issues I suspect this PR to causing the issue https://github.com/liamnichols/xcstrings-tool/pull/92/files. Or did I just misunderstood the usage? @liamnichols And thank you for this great library ❤️  

<img width="784" alt="Screenshot 2024-06-18 at 12 46 54" src="https://github.com/liamnichols/xcstrings-tool/assets/8895732/e5c6d642-7df1-4d4f-ad9a-03a09ba76cad">
<img width="769" alt="Screenshot 2024-06-18 at 12 47 17" src="https://github.com/liamnichols/xcstrings-tool/assets/8895732/b159304c-ff9a-447f-b60b-8f7175303d04">

**Comment by liamnichols** [comment]
Thanks for raising this @jmarek41! I've not seen this myself but from looking at the build log, it suggests that it is trying to build xcstrings-tool (the command line tool) for iOS, which shouldn't happen because this is a macOS utility that is used at build time.

When adding the xcstrings-tool package into your project, Xcode annoyingly suggests adding xcstrings-tool as a dependency to your targets, which you need to be sure to disable, it might be that this is the issue.

Could you double check the "Target Dependencies" under the "Build Phases" of your target to make sure that xcstrings-tool or StringsCatalog are not included. There should only be a reference to XCStringsToolPlugin under the "Run Build Tool Plug-ins" section for a correct configuration 🙇

**Comment by jmarek41** [comment]
Lol 😅. Sorry I overlooked it. Library was added as a dependency in my target. Thanks a lot for quick and helpful answer!

**Comment by liamnichols** [comment]
No worries, I don't know why Xcode does this. I should probably add a note to the docs (#102) to make that clear.

It's also worth noting that there are actually two ways you can add the dependency:

1. By adding the xcstrings-tool repo (this repo) - this is what you did
2. By adding the xcstrings-tool-plugin repo - this is what the docs suggest

xcstrings-tool-plugin contains the underlying command line tool as a precompiled binary artifact, so if you didn't already have swift-syntax in your dependency graph, it will help keep your clean builds nice and fast. 

Some people prefer to compile their tools from source though, so the choice is yours 👍
